### ISSUE TITLE
Make FORD Compatible

### ISSUE THREAD

**Issue by jatkinson1000** [cphyc/fortran-linter#86]
Hi, I really like this tool, thank you!

A lot of Fortran programmers use [FORD](https://forddocs.readthedocs.io/en/latest/index.html) to generate documentation for projects.

This relies on using `!!` or `!>` to denote FORD comments, which gets picked up as an error by the linter due to not having a space after the first `!`.

It would be great if the linter could be made FORD compatible and suppress warnings in these cases.

**Comment by cphyc** [comment]
Hi! Thanks for the feedback. I don't have much time to dedicate to the project anymore, but I'd be more than happy to include a Pull Request!

**Comment by jatkinson1000** [comment]
PR opened, thanks for considering.
Keen to use this in my projects!
